#!/bin/bash

# Push and Create PR Script for Concise LLaVA Prompts
# Generated by Claude Code

echo "🚀 Pushing branch to remote repository..."
git push -u origin feature/concise-llava-prompts

if [ $? -eq 0 ]; then
    echo "✅ Branch pushed successfully!"
    echo ""
    echo "📝 Creating pull request..."
    
    gh pr create \
        --title "feat: implement concise LLaVA analysis prompts" \
        --body "## Summary
Replace verbose default prompts with concise ones to get shorter, more focused AI analysis responses.

## Changes
- **Backend**: Change default prompt from \"Describe what you see in this image\" to \"Describe what is happening in 5 words or less\"
- **Frontend**: Update motion detection to use \"Describe in 5 words or less\" instead of long descriptive prompt  
- **Fix**: Correct Vite proxy target from port 8001 to 8000 for proper backend connection
- **Tests**: Update test assertions to match new default prompt

## Impact
This results in AI responses like \"person walking outside\" instead of lengthy descriptions, improving UX and reducing processing overhead.

## Benefits
- **Improved UX**: Shorter, more digestible analysis results
- **Reduced Processing**: Less token usage and faster responses
- **Better Performance**: Lighter network payload and faster rendering
- **Consistent Experience**: Uniform concise responses across all analysis

## Test Plan
- [x] Updated unit tests pass with new default prompts
- [x] Backend serves concise prompts by default
- [x] Frontend motion detection uses concise prompts
- [x] SSE connection works properly with corrected proxy configuration
- [x] AI analysis produces expected short-form responses

## Files Changed (4 files, 5 insertions, 5 deletions)
- Backend API prompt defaults
- Frontend motion detection prompt
- Vite proxy configuration fix
- Test assertions update

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
    
    if [ $? -eq 0 ]; then
        echo "✅ Pull request created successfully!"
        echo ""
        echo "🎉 All done! Your PR is ready for review."
        echo "The AI analysis will now provide concise responses like 'person walking outside'!"
    else
        echo "❌ Failed to create pull request. You may need to create it manually on GitHub."
    fi
else
    echo "❌ Failed to push branch. Please check your git configuration."
fi