#!/bin/bash

# Push and Create PR Script for AI Analysis Overlay System
# Generated by Claude Code

echo "🚀 Pushing branch to remote repository..."
git push -u origin feature/ai-analysis-overlay-system

if [ $? -eq 0 ]; then
    echo "✅ Branch pushed successfully!"
    echo ""
    echo "📝 Creating pull request..."
    
    gh pr create \
        --title "feat: implement AI analysis video overlay system with SSE integration" \
        --body "## Summary
- Implemented complete SSE (Server-Sent Events) integration for real-time communication
- Added AI analysis video overlays with LLaVA integration  
- Created throttled frame capture system for efficient AI processing
- Built responsive loading indicators and result displays with auto-dismiss functionality

## Key Features
- **SSE Service & Hooks**: Complete EventSource implementation with automatic reconnection
- **AI Analysis Overlays**: Glass morphism design with animations and progress indicators
- **Frame Capture**: Throttled 8-second intervals to prevent API overload
- **Loading States**: Real-time timer showing AI processing duration (15-60s typical)
- **Mobile Optimization**: Touch-friendly overlays and responsive design

## Technical Implementation
- **SSE Integration**: Event-driven updates for motion events and AI analysis results
- **Automatic Frame Capture**: Triggers on motion >20% with intelligent throttling
- **Type-Safe Architecture**: Full TypeScript integration with proper error handling
- **Performance Optimized**: Client-side filtering reduces backend load significantly

## Files Changed (16 files, 1,362 insertions)
- Core SSE integration and hooks
- AI analysis overlay components
- Frame capture utilities
- Loading indicators and animations
- Type definitions and API integration

## Test Plan
- [x] SSE connection and reconnection functionality
- [x] Motion detection triggering frame capture
- [x] AI analysis overlay display and auto-dismiss
- [x] Loading indicators during processing
- [x] Mobile responsive design
- [x] Error handling and graceful failures

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
    
    if [ $? -eq 0 ]; then
        echo "✅ Pull request created successfully!"
        echo ""
        echo "🎉 All done! Your PR is ready for review."
    else
        echo "❌ Failed to create pull request. You may need to create it manually on GitHub."
    fi
else
    echo "❌ Failed to push branch. Please check your git configuration."
fi