services:
  # React Frontend
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ../apps/web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
      - NODE_ENV=development
    depends_on:
      - api

  # FastAPI Backend
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ../apps/api:/app
    environment:
      - ENVIRONMENT=development
      - RELOAD=true
      - GEMINI_API_KEY=${GEMINI_API_KEY}